services:
  - type: web
    name: my-streamlit-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run test_app.py --server.port $PORT --server.address 0.0.0.0
    healthCheckPath: /
    healthCheckTimeout: 300
